version: "3"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    hostname: frontend
    volumes:
      - .:/app
    ports:
      - "80:80"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    hostname: backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
